# Site settings
title: kugtong33
email: sitoy.arjay@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  blah blah blah blah nothing fancy here as of the moment
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kugtong33.github.io" # the base hostname & protocol for your site
twitter_username: kugtong33
github_username: kugtong33

# Build settings
markdown: kramdown
